### ISSUE TITLE
Planlegg augustmøte 2018 - KeyCloak

### ISSUE THREAD

**Issue by elzapp** [BLUG/hugo-web#1]
Dato: 30. August 2018
Tidspunkt: 18:30 - 
Sted: Media City Bergen
Foredragsholder: Stian Thorgersen
Tema: KeyCloak

Referanser:
[KeyCloak](https://www.keycloak.org)
[Stian Thorgersen](https://github.com/stianst)
@stianst

**Comment by elzapp** [comment]
Skal vi prøve oss på en workshop i stedet for et vanlig foredrag? - Dvs et kortere foredrag, etterfulgt av en workshop der folk kan prøve å sette opp en integrasjon med keycloak?

**Comment by stianst** [comment]
Jeg kan ta et vanlig foredrag eller workshop. Opp til dere og hva dere helst vil ha.

**Comment by elzapp** [comment]
Innkalling er nå sendt ut i alle kanaler
